#define AST_TYPE_UNDEFINED 0
#define AST_TYPE_PROGRAM 1
#define AST_TYPE_VARIABLE_DECLARING 2
#define AST_TYPE_VARIABLE_SET_VALUE 3
#define AST_TYPE_VARIABLE_GET_VALUE 4
#define AST_TYPE_DEFFUNC 5
#define AST_TYPE_CODE_BLOCK 6
#define AST_TYPE_PARAMS 7
